// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Backend.Core.Entities.UserStackEntries;
using Backend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260826003115_AddSupplementLabelAssets")]
    partial class AddSupplementLabelAssets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Core.Entities.IntakeLogs.IntakeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContextualInstruction")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dosage")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IntendedTime")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SupplementName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("TakenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserStackEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserStackEntryId");

                    b.HasIndex("UserId", "TakenAtUtc");

                    b.HasIndex("UserId", "UserStackEntryId", "TakenAtUtc");

                    b.ToTable("IntakeLogs");
                });

            modelBuilder.Entity("Backend.Core.Entities.Supplements.ProductIngredient", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DosageAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("DosageUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ProductId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ProductIngredients");
                });

            modelBuilder.Entity("Backend.Core.Entities.Supplements.SupplementIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("Aliases")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalName")
                        .IsUnique();

                    b.ToTable("SupplementIngredients");
                });

            modelBuilder.Entity("Backend.Core.Entities.Supplements.SupplementProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DsldId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LabelAssetsFetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LabelPdfUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("DsldId")
                        .IsUnique();

                    b.ToTable("SupplementProducts");
                });

            modelBuilder.Entity("Backend.Core.Entities.UserStackEntries.UserStackEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContextualInstruction")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<StackCustomization>("Cusomization")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CustomName")
                        .HasColumnType("text");

                    b.Property<string>("IntendedTime")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ServingMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int?>("SupplementProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SupplementProductId");

                    b.HasIndex("UserId", "IsActive", "IntendedTime");

                    b.ToTable("UserStackEntries");
                });

            modelBuilder.Entity("Backend.Core.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Core.Entities.IntakeLogs.IntakeLog", b =>
                {
                    b.HasOne("Backend.Core.Entities.UserStackEntries.UserStackEntry", "UserStackEntry")
                        .WithMany()
                        .HasForeignKey("UserStackEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserStackEntry");
                });

            modelBuilder.Entity("Backend.Core.Entities.Supplements.ProductIngredient", b =>
                {
                    b.HasOne("Backend.Core.Entities.Supplements.SupplementIngredient", "Ingredient")
                        .WithMany("ProductLinks")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Core.Entities.Supplements.SupplementProduct", "Product")
                        .WithMany("ActiveIngredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Core.Entities.UserStackEntries.UserStackEntry", b =>
                {
                    b.HasOne("Backend.Core.Entities.Supplements.SupplementProduct", "SupplementProduct")
                        .WithMany()
                        .HasForeignKey("SupplementProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SupplementProduct");
                });

            modelBuilder.Entity("Backend.Core.Entities.Supplements.SupplementIngredient", b =>
                {
                    b.Navigation("ProductLinks");
                });

            modelBuilder.Entity("Backend.Core.Entities.Supplements.SupplementProduct", b =>
                {
                    b.Navigation("ActiveIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
